# Generated by Django 4.2.6 on 2023-11-09 05:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0005_remove_userprofile_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='blog_card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_title', models.CharField(default='Lucknow', max_length=100)),
                ('blog_desc', models.CharField(default=' ', max_length=20)),
                ('blog_image', models.ImageField(default='', upload_to='media')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_name', models.CharField(max_length=20)),
                ('cat_image', models.ImageField(upload_to='media')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('orderId', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('date_ordered', models.DateTimeField(auto_now_add=True)),
                ('payment_method', models.CharField(choices=[('credit_card', 'Credit Card'), ('cash_on_delivery', 'Cash on Delivery')], max_length=20)),
                ('order_status', models.CharField(choices=[('created', 'Created'), ('shipped', 'Shipped'), ('processed', 'Processed'), ('completed', 'Completed')], default='created', max_length=20)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('productId', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=20, null=True)),
                ('price', models.FloatField(max_length=6)),
                ('category', models.CharField(choices=[('fabric', 'Fabric'), ('kurti', 'Kurti'), ('saree', 'Saree')], max_length=50)),
                ('main_image', models.ImageField(upload_to='media')),
                ('img1', models.ImageField(null=True, upload_to='media')),
                ('img2', models.ImageField(null=True, upload_to='media')),
                ('img3', models.ImageField(null=True, upload_to='media')),
                ('color', models.CharField(default=' ', max_length=20, null=True)),
                ('fabrics', models.CharField(blank=True, max_length=20, null=True)),
                ('embroidery', models.CharField(blank=True, max_length=20, null=True)),
                ('embroidery_color', models.CharField(blank=True, max_length=20, null=True)),
                ('washing_instrutions', models.CharField(blank=True, max_length=100, null=True)),
                ('dyeing', models.CharField(blank=True, max_length=50, null=True)),
                ('product_description', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Saree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.product')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0, null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='homepage.order')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='homepage.product')),
            ],
        ),
        migrations.CreateModel(
            name='Kurti',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.product')),
            ],
        ),
        migrations.CreateModel(
            name='Fabric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.product')),
            ],
        ),
        migrations.CreateModel(
            name='Bestseller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(default=' ', on_delete=django.db.models.deletion.CASCADE, to='homepage.product')),
            ],
        ),
    ]
