# Generated by Django 4.2.6 on 2023-11-10 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('debit_card', 'DEBIT CARD'), ('credit_card', 'Credit Card'), ('upi', 'UPI'), ('cash_on_delivery', 'Cash on Delivery')], max_length=20),
        ),
    ]
