# Generated by Django 4.2.6 on 2023-11-10 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_alter_order_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='kurti',
            name='l42',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='kurti',
            name='m40',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='kurti',
            name='s38',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='kurti',
            name='xl44',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='kurti',
            name='xs36',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='kurti',
            name='xxl48',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
