# Generated by Django 4.2.6 on 2023-11-10 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_kurti_l42_kurti_m40_kurti_s38_kurti_xl44_kurti_xs36_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kurti',
            name='l42',
        ),
        migrations.RemoveField(
            model_name='kurti',
            name='m40',
        ),
        migrations.RemoveField(
            model_name='kurti',
            name='s38',
        ),
        migrations.RemoveField(
            model_name='kurti',
            name='xl44',
        ),
        migrations.RemoveField(
            model_name='kurti',
            name='xs36',
        ),
        migrations.RemoveField(
            model_name='kurti',
            name='xxl48',
        ),
    ]
