# Generated by Django 4.2.6 on 2023-11-11 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0005_kurti_available_sizes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Fabric', 'fabric'), ('Kurti', 'kurti'), ('Saree', 'saree')], max_length=50),
        ),
    ]
