# Generated by Django 4.2.6 on 2023-11-13 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_remove_userprofile_email_and_more'),
        ('homepage', '0008_order_address_order_city_order_contact_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='productitem',
        ),
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.userprofile'),
        ),
    ]
