# Generated by Django 4.2.6 on 2023-11-16 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0015_alter_order_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitems',
            name='size_selected',
            field=models.CharField(default='', max_length=20),
        ),
    ]
