# Generated by Django 4.2.6 on 2023-11-16 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0016_orderitems_size_selected'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitems',
            name='size_selected',
            field=models.CharField(default='', max_length=20, null=True),
        ),
    ]
