# Generated by Django 4.2.6 on 2023-11-24 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0019_order_tracking_id_order_tracking_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bannerimg',
            fields=[
                ('imgid', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(null=True, upload_to='media')),
            ],
        ),
    ]
