# Generated by Django 4.2.6 on 2023-11-28 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0020_bannerimg'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoryContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('story_title', models.CharField(max_length=20, null=True)),
                ('story_content', models.TextField(max_length=500, null=True)),
                ('stroy_image', models.ImageField(null=True, upload_to='media')),
            ],
        ),
    ]
