# Generated by Django 4.2.6 on 2023-11-28 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0027_alter_cancelrefund_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, null=True)),
                ('about', models.TextField(max_length=5000, null=True)),
                ('about_image', models.ImageField(null=True, upload_to='media')),
            ],
        ),
    ]
