# Generated by Django 4.2.6 on 2023-11-28 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0030_alter_about_about'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='about_image',
        ),
    ]
