# Generated by Django 4.2.6 on 2024-03-10 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0031_remove_about_about_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('Cash on Delivery', 'cash_on_delivery'), ('Pay Online', 'pay_online')], max_length=20),
        ),
    ]
