# Generated by Django 4.2.6 on 2023-10-22 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_rename_firstname_userprofile_first_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='e_mail',
            new_name='email',
        ),
    ]
