# Generated by Django 4.2.6 on 2023-10-22 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_rename_e_mail_userprofile_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='user',
            new_name='users',
        ),
    ]
